var app = angular.module( 'app', [] );

app.controller( 'main', [ '$scope', '$filter', function($scope, $filter){
	$scope.docs = [
		{
			"title":"How the documentation is organized",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"First steps",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"The model layer",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"The view layer",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"The template layer",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"Forms",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"The development process",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"The admin",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
		{
			"title":"Security",
			"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed enim nec dui molestie mollis vel in lacus. Ut in tortor nec lacus malesuada pretium. Quisque pretium elit et maximus rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut vitae viverra lectus. Duis at diam sit amet nisi pellentesque tempus. Morbi consequat vehicula dolor ac egestas. Nullam enim ante, egestas sed massa at, consectetur aliquam quam. Suspendisse maximus leo vitae odio placerat, quis mollis tortor ultrices. Donec at lacus sit amet metus suscipit lacinia. Cras eu ipsum scelerisque, suscipit dolor luctus, rutrum enim. Curabitur quis sem viverra lorem viverra condimentum. Nunc gravida molestie ex, et elementum urna vulputate sit amet. Aliquam erat volutpat. In hac habitasse platea dictumst. Duis dolor turpis, venenatis quis risus at, placerat tempor leo. "
		},
	]
}]);